file=open("D:/grrades.txt","r")
grades=file.readline()
for i in grades:
    Aminus=grades.count("A-")
    A = grades.count("A ")
    Bminus=grades.count("B-")
    B=grades.count("B ")
    Bplus=grades.count("B+")
    C = grades.count("C ")
    Cminus=grades.count("C-")
    Cplus=grades.count("C+")
    D=grades.count('D ')
    F=grades.count("F ")
print(Aminus," students got A- .")
print(A," students got A")
print(B," students got B")
print(Bminus," students got B- ")
print(Bplus," students got B+ ")
print(Cplus," students got C+ ")
print(Cminus," students got C-")
print(C," students got C ")
print(D," students got D")
print(F," students got F")

